
# Dynamic port binding required by Render
server.port=${PORT:8080}

# Database connection using Render's Internal Database URL variable
spring.datasource.url=jdbc:${postgresql://message_db_zpzo_user:TTsDmE9Yrytmi6qMX3YnVfMTXT5CAVfr@dpg-d8sdn5mrnols738h8tt0-a/message_db_zpzo}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate DDL settings for production safety
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
